### ISSUE TITLE
Go use web components

### ISSUE THREAD

**Issue by Chnapy** [geauser/bricks#1]
![3d1](https://user-images.githubusercontent.com/7474483/77761359-36e9e880-7038-11ea-84d1-d223862d1995.jpg)

Did you think about using Web Components ? No you didn't i know. https://www.polymer-project.org/

it allows to not limit the use of your lib to a single renderer (vue, react,..). So real devs who do not use vuejs can use your lib.

**Comment by geauser** [comment]
Hi @Chnapy thanks for the feedback
